blank_issues_enabled: false
contact_links:
  - name: Questions and help
    url: https://github.com/oussamabouchareb/op-tools/discussions
    about: This is a bug tracker, not a support system. For usage questions, please use our support resources.
