name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Test Suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Check formatting
        run: yarn format:check

      - name: Lint code
        run: yarn lint

      - name: Run Tests
        run: yarn test
